package com.bank.ea.config;
import com.bank.ea.domain.CatalogItem; import com.bank.ea.repo.CatalogRepository; import java.util.List; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration;
@Configuration public class DemoDataConfig {
 private static final List<String> OLD=List.of("Core Banking Platform","Mobile Banking","AML Transaction Monitoring","Java 21 LTS","Java 8","PostgreSQL","Mobile Banking Authentication Upgrade","Payments Event Streaming","Unsupported Java Runtime","Point-to-point integration concentration","Customer Profile API","Payment Initiation API");
 @Bean CommandLineRunner mpmProjectData(CatalogRepository r){return args->{OLD.forEach(n->r.findByName(n).ifPresent(r::delete));
  add(r,CatalogItem.Type.APPLICATION,"MPM Leasing CRM","Dynamics 365 solution for property inventory, prospects, leasing opportunities, contracts and renewals.","MPM CRM Product Owner",CatalogItem.Status.UNDER_REVIEW,"Critical","Confidential","2026-12-15");
  add(r,CatalogItem.Type.APPLICATION,"Property & Unit Management","Master view of buildings, properties, units, availability, pricing and amenities.","Leasing Operations",CatalogItem.Status.DRAFT,"Critical","Confidential","2026-09-30");
  add(r,CatalogItem.Type.APPLICATION,"Tenant 360","Customer and tenant profile with enquiries, viewings, offers, leases, cases and communication history.","Customer Experience",CatalogItem.Status.DRAFT,"High","Restricted","2026-10-31");
  add(r,CatalogItem.Type.APPLICATION,"Lease Lifecycle Management","Quotation, reservation, approval, contract activation, renewal, termination and handover.","Leasing Operations",CatalogItem.Status.UNDER_REVIEW,"Critical","Restricted","2026-11-30");
  add(r,CatalogItem.Type.TECHNOLOGY,"Microsoft Dynamics 365 Sales","Core CRM platform for leads, opportunities, accounts, contacts and leasing extensions.","Solution Architecture",CatalogItem.Status.APPROVED,"Critical","Internal","2027-06-30");
  add(r,CatalogItem.Type.TECHNOLOGY,"Microsoft Dataverse","Primary data platform for CRM business tables, security roles, auditing and solution deployment.","Data Architecture",CatalogItem.Status.APPROVED,"Critical","Restricted","2027-06-30");
  add(r,CatalogItem.Type.TECHNOLOGY,"Power Automate","Workflow automation for approvals, notifications and controlled integration orchestration.","Power Platform CoE",CatalogItem.Status.APPROVED,"High","Internal","2027-03-31");
  add(r,CatalogItem.Type.TECHNOLOGY,"Power Pages","Candidate technology for broker, landlord or tenant self-service journeys.","Digital Architecture",CatalogItem.Status.UNDER_REVIEW,"High","Confidential","2026-10-15");
  add(r,CatalogItem.Type.REVIEW,"Property and Unit Data Model","Validate property hierarchy, availability, pricing, ownership and Dataverse relationships.","CRM Solution Architect",CatalogItem.Status.UNDER_REVIEW,"Critical","Confidential","2026-08-15");
  add(r,CatalogItem.Type.REVIEW,"Lease Approval Workflow","Review approval thresholds, segregation of duties, discount controls and exception handling.","Business Process Owner",CatalogItem.Status.DRAFT,"Critical","Restricted","2026-08-31");
  add(r,CatalogItem.Type.REVIEW,"Dynamics Security Model","Review business units, teams, field security, privileged roles and tenant-data access.","Information Security",CatalogItem.Status.UNDER_REVIEW,"Critical","Restricted","2026-09-15");
  add(r,CatalogItem.Type.RISK,"Property availability synchronisation","Delayed source updates may allow multiple agents to offer the same unit.","Integration Lead",CatalogItem.Status.ACTIVE,"Critical","Confidential","2026-09-30");
  add(r,CatalogItem.Type.RISK,"Duplicate customer and tenant records","Uncontrolled lead capture may produce duplicates and an inaccurate Tenant 360 view.","CRM Data Lead",CatalogItem.Status.ACTIVE,"High","Restricted","2026-10-15");
  add(r,CatalogItem.Type.RISK,"Excessive Dynamics privileges","Broad security roles could expose confidential customer, pricing or contract information.","Information Security",CatalogItem.Status.UNDER_REVIEW,"Critical","Restricted","2026-09-15");
  add(r,CatalogItem.Type.API,"Property Inventory Integration","Synchronises properties, units, availability, rent, fees and unit status into Dataverse.","Integration Team",CatalogItem.Status.UNDER_REVIEW,"Critical","Confidential","2026-09-30");
  add(r,CatalogItem.Type.API,"Finance and Contract Integration","Sends approved lease contracts, charges and payment schedules to the finance platform.","Finance Systems",CatalogItem.Status.DRAFT,"Critical","Restricted","2026-11-15");
  add(r,CatalogItem.Type.API,"Document Management Integration","Stores tenant documents and signed lease contracts in the approved repository.","Content Management",CatalogItem.Status.DRAFT,"High","Restricted","2026-10-31");
  add(r,CatalogItem.Type.API,"Email and SMS Notifications","Sends viewing confirmations, offer updates, approval notices and renewal reminders.","Customer Experience",CatalogItem.Status.UNDER_REVIEW,"High","Confidential","2026-10-15");
 };}
 private void add(CatalogRepository r,CatalogItem.Type t,String n,String d,String o,CatalogItem.Status s,String c,String x,String date){if(r.findByName(n).isPresent())return;CatalogItem i=new CatalogItem();i.setType(t);i.setName(n);i.setDescription(d);i.setOwner(o);i.setStatus(s);i.setCriticality(c);i.setClassification(x);i.setTargetDate(date);r.save(i);}
}
