package com.bank.ea.web;
import com.bank.ea.domain.*; import com.bank.ea.repo.*; import jakarta.validation.Valid; import java.security.Principal; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller public class ProjectController {private final ProjectRepository projects;private final AuditRepository audits;ProjectController(ProjectRepository p,AuditRepository a){projects=p;audits=a;}
 @GetMapping("/projects") String list(Model m){m.addAttribute("projects",projects.findAllByOrderByUpdatedAtDesc());return "projects";}
 @GetMapping("/projects/new") String create(Model m){form(m,new Project());return "project-form";}
 @GetMapping("/projects/{id}") String edit(@PathVariable Long id,Model m){form(m,projects.findById(id).orElseThrow());return "project-form";}
 @PostMapping("/projects/save") String save(@Valid @ModelAttribute Project submitted,BindingResult errors,Principal principal,Model m,RedirectAttributes flash){if(errors.hasErrors()){form(m,submitted);return "project-form";}boolean fresh=submitted.getId()==null;Project record=fresh?submitted:projects.findById(submitted.getId()).orElseThrow();if(!fresh)copy(submitted,record);Project saved=projects.save(record);audits.save(new AuditEvent(principal.getName(),fresh?"CREATE":"UPDATE","PROJECT",saved.getId().toString(),saved.getName()+" -> "+saved.getStage()));flash.addFlashAttribute("message","Project saved successfully");return "redirect:/projects";}
 private void form(Model m,Project p){m.addAttribute("project",p);m.addAttribute("stages",Project.Stage.values());}
 private void copy(Project s,Project t){t.setName(s.getName());t.setCode(s.getCode());t.setSponsor(s.getSponsor());t.setBusinessOwner(s.getBusinessOwner());t.setLeadArchitect(s.getLeadArchitect());t.setStage(s.getStage());t.setStartDate(s.getStartDate());t.setTargetDate(s.getTargetDate());t.setOverallRisk(s.getOverallRisk());t.setProblemStatement(s.getProblemStatement());t.setApprovalAuthority(s.getApprovalAuthority());t.setMandatoryInformation(s.getMandatoryInformation());t.setExistingTools(s.getExistingTools());t.setSsoRequirements(s.getSsoRequirements());t.setSecurityRequirements(s.getSecurityRequirements());t.setHostingRequirements(s.getHostingRequirements());t.setRetentionRequirements(s.getRetentionRequirements());t.setExecutiveReports(s.getExecutiveReports());t.setAuditEvidence(s.getAuditEvidence());t.setRepositoryOwner(s.getRepositoryOwner());t.setRepositoryMaintainer(s.getRepositoryMaintainer());}
}
